- name: variables
  hosts: all
  vars:
    my_var: "Hello, World!"
    URL: playbook.google.com
  tasks:
    - name: Display a variable
      ansible.builtin.debug:
        msg: "The value of my_var is {{ my_var }}"
    - name: Display a fact
      ansible.builtin.debug:
        msg: "The URL name is {{ URL }}"