- name: variables
  hosts: all
  vars:
    my_var: "Hello, World!"
    URL: play.google.com   # playbook variable
  tasks:
    - name: Display a variable
      ansible.builtin.debug:
        msg: "The value of my_var is {{ my_var }}"
    - name: Display a URL
      ansible.builtin.debug:
        msg: "The URL name is {{ URL }}"
    - name: Printing a URL in task level
      ansible.builtin.debug:
        msg: "The value of URL is:  {{ URL }}"
      vars:
        URL: "task.google.com"      #task level variable