- name: FileVariable
  hosts: all
  vars:
    URL: play.google.com   # playbook variable
  vars_files:
    - "{{ env }}-vars.yml"
  tasks:
    - name: Printing variable from file
      ansible.builtin.debug:
        msg: "The value is fetched from the file. and the environment value is  {{ ENV }} and the group value is {{ Group }} and the project value is {{ Project }}"
   