- name: Demo on Errors
  hosts: all
  tasks:
    - name: task1
      ansible.builtin.shell: df -h
      register: result
    - name: printing the output
      ansible.builtin.debug:
        msg: "The output is: {{ result.result.stdout }}"  

    - name: task2
      ansible.builtin.shell: df -h | grep /ravi
      register: result
      ignore_errors: yes  # Ignore errors for this task
    - name: printing the output
      ansible.builtin.debug:
        msg: "The output is: {{ result }}" 
