- name: Demo on tags, if you want skip to print frontend and db, you can use --skip-tags frontend,db and want to print only backend, you can use --tags backend then use tags in command line
  hosts: all
  gather_facts: no  # if you want to skip the facts gathering, you can use this option
  tasks:
    - name: install frontend
      ansible.builtin.debug:
        msg: "insatll frontend"
      tags: frontend

    - name: start frontend
      ansible.builtin.debug:
        msg: "start frontend"
      tags: frontend

    - name: install backend
      ansible.builtin.debug:
        msg: "insatll backend"
      tags: backend

    - name: start backend
      ansible.builtin.debug:
        msg: "start backend"
      tags: backend

    - name: install db
      ansible.builtin.debug:
        msg: "insatll DB"
      tags: db
      
    - name: start DB
      ansible.builtin.debug:
        msg: "start DB"
      tags: frondbtend
     