- name: install nginx package   
  hosts: all
  become: yes # become to root user
  gather_facts: no  # if you want to skip the facts gathering, you can use this option
  tasks:
    - name: Install package
      ansible.builtin.package:
        name: nginx
        state: present
      register: result
    - name: print the result
      ansible.builtin.debug:
        msg: "The result is: {{ result }}"